#!/usr/bin/env bash
# save current
cp /etc/hosts /etc/hosts.backup
# delete for localhost of /etc/hosts
echo -n > /etc/hosts
# localhost to 127.0.0.1
echo "127.0.0.2 localhost" >> /etc/hosts
# facebook to 8.8.8.8
echo "8.8.8.8 facebook.com" >> /etc/hosts
